# Generated by Django 5.2.5 on 2026-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statut_personnalise',
            field=models.CharField(blank=True, default='Disponible sur Kozons', max_length=80),
        ),
    ]
